### ISSUE TITLE
nodes click event not fired on touch device

### ISSUE THREAD

**Issue by dennisverspuij** [algrx/algorithmx-demo#1]
Hello, compliments for this awesome library.
I experience one issue with it, click events on nodes are not firing on mobile/touch devices.
Visit the [NodeSelection click demo](https://algrx.github.io/api/NodeSelection/click/) with Chrome on an Android phone and you'll notice clicks on the node won't do anything.
May be this has to do with the drag handlers stopping propagation?
Hope this can be fixed easily, tia!

**Comment by alexsocha** [comment]
Thanks for the feedback! You were right about this being an issue with drag propagation - should be fixed now!

**Comment by dennisverspuij** [comment]
Hi Alex, huge thanks for the quick fix!
